<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Cores\Models\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UstamYolda.Infastructure\UstamYolda.Infastructure.csproj" />
  </ItemGroup>

</Project>
